version: 2
updates:
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - withlogicco/hq
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  
  # Fetch and update latest `python` packages
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - withlogicco/hq
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # Fetch and update base docker image
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - withlogicco/hq
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
