name: CI

on:
  push:
    branches:
      - main

env:
  POETRY_VERSION: 1.1.6

jobs:
  poetry:
    name: Poetry version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/parisk/poetry:${{ env.POETRY_VERSION }}
          build-args: |
            POETRY_VERSION=${{ env.POETRY_VERSION }}

  poetry_and_python:
    name: Poetry with Python version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
        poetry: ["1.1.6"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: ${{ env.POETRY_VERSION }}-python-${{ matrix.python }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/parisk/poetry:${{ env.POETRY_VERSION }}-python-${{ matrix.python }}
          build-args: |
            POETRY_VERSION=${{ env.POETRY_VERSION }}
            PYTHON_VERSION=${{ matrix.python }}
            VARIANT=buster
      - name: ${{ env.POETRY_VERSION }}-python-${{ matrix.python }}-alpine
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/parisk/poetry:${{ env.POETRY_VERSION }}-python-${{ matrix.python }}-alpine
          build-args: |
            POETRY_VERSION=${{ env.POETRY_VERSION }}
            PYTHON_VERSION=${{ matrix.python }}
            VARIANT=alpine
      - name: ${{ env.POETRY_VERSION }}-python-${{ matrix.python }}-slim
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/parisk/poetry:${{ env.POETRY_VERSION }}-python-${{ matrix.python }}-slim
          build-args: |
            POETRY_VERSION=${{ env.POETRY_VERSION }}
            PYTHON_VERSION=${{ matrix.python }}
            VARIANT=slim
