name: Release

on: push

env:
  POETRY_VERSION: "1.1.13"
  GHCR_IMAGE_REPOSITORY: ghcr.io/${{ github.repository_owner }}/poetry
  GHCR_IMAGE_TAG: "1.1.13"

jobs:
  poetry:
    name: Poetry version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.GHCR_IMAGE_REPOSITORY }}:${{ env.GHCR_IMAGE_TAG }}
          build-args: |
            POETRY_VERSION=${{ env.POETRY_VERSION }}

  poetry_and_python:
    name: Poetry with Python version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: ${{ env.POETRY_VERSION }}-python-${{ matrix.python }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.GHCR_IMAGE_REPOSITORY }}:${{ env.GHCR_IMAGE_TAG }}-python-${{ matrix.python }}
          build-args: |
            POETRY_VERSION=${{ env.POETRY_VERSION }}
            PYTHON_VERSION=${{ matrix.python }}
            VARIANT=buster
      - name: ${{ env.POETRY_VERSION }}-python-${{ matrix.python }}-alpine
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.GHCR_IMAGE_REPOSITORY }}:${{ env.GHCR_IMAGE_TAG }}-python-${{ matrix.python }}-alpine
          build-args: |
            POETRY_VERSION=${{ env.POETRY_VERSION }}
            PYTHON_VERSION=${{ matrix.python }}
            VARIANT=alpine
      - name: ${{ env.POETRY_VERSION }}-python-${{ matrix.python }}-slim
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.GHCR_IMAGE_REPOSITORY }}:${{ env.GHCR_IMAGE_TAG }}-python-${{ matrix.python }}-slim
          build-args: |
            POETRY_VERSION=${{ env.POETRY_VERSION }}
            PYTHON_VERSION=${{ matrix.python }}
            VARIANT=slim
