name: Release

on: push

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      poetry_version: "1.1.3"
      python_version: ${{ matrix.python_version }}
      ghcr_image_base_tag: ${{ github.event.release.tag_name }}
    strategy:
      matrix:
        python_version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
