name: Release

on:
  release:
    types: [published]

env:
  POETRY_VERSION: "1.1.13"

jobs:
  build:
    name: Poetry with Python version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    uses: ./.github/workflows/build.yml
    with:
      poetry_version: ${{ env.POETRY_VERSION }}
      python_version: ${{ matrix.python_version }}
      ghcr_image_base_tag: ${{ github.event.release.tag_name }}
    secrets:
      github_token: ${{ secrets/GITHUB_TOKEN }}
