name: Release

on:
  release:
    types: [published]

env:
  POETRY_VERSION: 1.1.13
  GHCR_IMAGE_REPOSITORY: ghcr.io/${{ github.repository_owner }}/poetry

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        variant:
          - buster
          - slim
          - alpine
        include:
          - python: "3.10"
            is_default_python: true
          - variant: buster
            is_default_variant: true
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64,arm
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Python + Variant: ${{ env.POETRY_VERSION }}-python-${{ matrix.python }}-${{ matrix.variant }}"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.GHCR_IMAGE_REPOSITORY }}:${{ env.POETRY_VERSION }}-python-${{ matrix.python }}-${{ matrix.variant }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm,linux/arm/v6
          build-args: |
            POETRY_VERSION=${{ env.POETRY_VERSION }}
            PYTHON_VERSION=${{ matrix.python }}
            VARIANT=${{ matrix.variant }}
      - name: "Python + Default Variant: ${{ env.POETRY_VERSION }}-python-${{ matrix.python }}"
        uses: docker/build-push-action@v2
        if: matrix.is_default_variant
        with:
          push: true
          tags: ${{ env.GHCR_IMAGE_REPOSITORY }}:${{ env.POETRY_VERSION }}-python-${{ matrix.python }}
          platforms: linux/amd64,linux/arm64,linux/arm,linux/arm/v6
          build-args: |
            POETRY_VERSION=${{ env.POETRY_VERSION }}
            PYTHON_VERSION=${{ matrix.python }}
            VARIANT=${{ matrix.variant }}
      - name: "Default Python + Variant: ${{ env.POETRY_VERSION }}-${{ matrix.variant }}"
        uses: docker/build-push-action@v2
        if: matrix.is_default_python
        with:
          push: true
          tags: ${{ env.GHCR_IMAGE_REPOSITORY }}:${{ env.POETRY_VERSION }}-${{ matrix.variant }}
          platforms: linux/amd64,linux/arm64,linux/arm,linux/arm/v6
          build-args: |
            POETRY_VERSION=${{ env.POETRY_VERSION }}
            PYTHON_VERSION=${{ matrix.python }}
            VARIANT=${{ matrix.variant }}
      - name: "Default Python + Default Variant: ${{ env.POETRY_VERSION }}"
        uses: docker/build-push-action@v2
        if: matrix.is_default_python && matrix.is_default_variant
        with:
          push: true
          tags: ${{ env.GHCR_IMAGE_REPOSITORY }}:${{ env.POETRY_VERSION }}
          platforms: linux/amd64,linux/arm64,linux/arm,linux/arm/v6
          build-args: |
            POETRY_VERSION=${{ env.POETRY_VERSION }}
            PYTHON_VERSION=${{ matrix.python }}
            VARIANT=${{ matrix.variant }}
